root_path: C:/Users/ID_Admin/Downloads/OSCD/coco_carton/oneclass_carton
train_json: annotations/instances_train2017.json
train_images: images/train2017
val_json: annotations/instances_val2017.json
val_images: images/val2017
model_config: COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml
num_classes: 1
num_workers: 2
ims_per_batch: 2
base_lr: 0.00025
max_iter: 1000
batch_size_per_image: 128
output_dir: output
