root_path: C:/Users/ID_Admin/Downloads/OSCD/coco_carton/oneclass_carton

# Dataset
train_json: annotations/instances_train2017.json
train_images: images/train2017
val_json: annotations/instances_val2017.json
val_images: images/val2017

# Model
model_config: COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml
num_classes: 1

# DataLoader
num_workers: 2

# Training
ims_per_batch: 4              # ↑ from 2 → better GPU utilization
batch_size_per_image: 256     # ↑ more region proposals
base_lr: 0.00025
max_iter: 10000               # ↑ from 1000 → trains longer = better learning

# Output
output_dir: C:/Users/ID_Admin/Desktop/work/git/playground/JacobiRoboticsChallenge/box_segmentation/model
